### ISSUE TITLE
Commit broke Qwiklab 

### ISSUE THREAD

**Issue by falico** [GoogleCloudPlatform/istio-samples#50]
I was going through the "AHYBRID060 Managing Policies and Security with Istio and Citadel" lab from Coursera specialization ("Hybrid Cloud Service Mesh with Anthos" course) and found out that it was broken. The problem is that the lab requires Hipstershop and it is not there in last version.

After some analysis, I've found out that the problem was generated by the commit 3f286963ec49403b229689bf70cdc501249d9eec.

Getting the previous version solved my problem.

**Comment by tzehon** [comment]
Ran into this issue as well, worked around it in an identical fashion (checking out the previous commit)

**Comment by askmeegs** [comment]
Hi Rodrigo, thank you for the heads-up! Fix in progress, will keep you posted.

**Comment by miketruty** [comment]
I've got this fixed. I'm working through testing now.

**Comment by askmeegs** [comment]
@miketruty okay to close this?

**Comment by miketruty** [comment]
The fix is done and tested. The fix-push is happening. OK with me if you close. Thank you commenters for raising this!

**Comment by miketruty** [comment]
Fix has been pushed out.
