### ISSUE TITLE
Problem trying to create a docker image

### ISSUE THREAD

**Issue by lucasgvarela** [GoogleCloudPlatform/istio-samples#56]
I was following this tutorial: https://cloud.google.com/istio/docs/prepare-app-for-istio, and in the step "Build the image using the Dockerfile and the environment variables that you defined previously:", I'm receiving one error:

`Step 8/11 : COPY --from=builder /usr/local/lib/python3.7/ /usr/local/lib/python3.7/
COPY failed: stat /var/lib/docker/overlay2/5efac87e95d4a1da9d4b0e75469006d99900ec5e2fcaf340306e17013a7b99cd/merged/usr/local/lib/python3.7: no such file or directory`

![image](https://user-images.githubusercontent.com/37870368/75291897-e47f9700-5801-11ea-8833-14567dcc1ad9.png)

Path to the Dockerfile: /istio-samples/sample-apps/helloserver/server/Dockerfile

*This is my first time opening an issue, if there is something wrong or if some information is missing, please inform me and will be glad to provide.

**Comment by lucasgvarela** [comment]
I entered in the interactive mode for docker, for the python image that is being used in that Dockerfile, and I discovered we do not have /usr/local/lib/python3.7 anymore, but /usr/local/lib/python3.8 now.

`#ls -ld /usr/local/lib/python*
drwxr-xr-x 1 root root 4096 Feb 26 15:10 /usr/local/lib/python3.8`

`lucasgvarela99@cloudshell:~/istio-samples/sample-apps/helloserver/server (istio-269321)$ docker build -t gcr.io/$PROJECT_ID/$GCR_REPO/helloserver:v0.0.1 .
Sending build context to Docker daemon  7.168kB
Step 1/11 : FROM python:3-slim as base
 ---> ee07b1466448
Step 2/11 : FROM base as builder
 ---> ee07b1466448
Step 3/11 : RUN apt-get -qq update     && apt-get install -y --no-install-recommends         g++     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> c0ca8a461f47
Step 4/11 : FROM base as final
 ---> ee07b1466448
Step 5/11 : ENV PYTHONUNBUFFERED=1
 ---> Using cache
 ---> 51c1cd10842b
Step 6/11 : RUN apt-get -qq update     && apt-get install -y --no-install-recommends         wget
 ---> Using cache
 ---> 278b864f86f2
Step 7/11 : WORKDIR /helloserver
 ---> Using cache
 ---> 66425622f920
Step 8/11 : COPY --from=builder /usr/local/lib/python3.8/ /usr/local/lib/python3.8/
 ---> 5bf73c032b82
Step 9/11 : COPY . .
 ---> 4aac4e756d15
Step 10/11 : EXPOSE 8080
 ---> Running in 603e6869a1c2
Removing intermediate container 603e6869a1c2
 ---> 0637e2ec3677
Step 11/11 : ENTRYPOINT [ "python", "server.py" ]
 ---> Running in b6a4e0020362
Removing intermediate container b6a4e0020362
 ---> 7628202a37c0
Successfully built 7628202a37c0
Successfully tagged gcr.io/istio-269321/preparing-istio/helloserver:v0.0.1
lucasgvarela99@cloudshell:~/istio-samples/sample-apps/helloserver/server (istio-269321)$ cat Dockerfile
FROM python:3-slim as base
FROM base as builder
RUN apt-get -qq update \
    && apt-get install -y --no-install-recommends \
        g++ \
    && rm -rf /var/lib/apt/lists/*

# Enable unbuffered logging
FROM base as final
ENV PYTHONUNBUFFERED=1

RUN apt-get -qq update \
    && apt-get install -y --no-install-recommends \
        wget

WORKDIR /helloserver

# Grab packages from builder
COPY --from=builder /usr/local/lib/python3.8/ /usr/local/lib/python3.8/

# Add the application
COPY . .

EXPOSE 8080
ENTRYPOINT [ "python", "server.py" ]`

**Comment by askmeegs** [comment]
Hi Lucas, thanks for catching this! Updating the Dockerfiles to use 3.8.
