### ISSUE TITLE
chore: snippet-bot full scan

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/istio-samples#69]
## snippet-bot scan result
Life is too short to manually check unmatched region tags.
Here is the result:
- [ ] [multicluster-gke/dual-control-plane/cluster1/deployments.yaml:53](https://github.com/GoogleCloudPlatform/istio-samples/blob/541050f/multicluster-gke/dual-control-plane/cluster1/deployments.yaml#L53), tag `istio_dual_control_plane_cluster1_deployment_emailservice` doesn't have a matching start tag.
- [ ] [multicluster-gke/vm-migration/cluster1/deployments.yaml:53](https://github.com/GoogleCloudPlatform/istio-samples/blob/541050f/multicluster-gke/vm-migration/cluster1/deployments.yaml#L53), tag `istio_dual_control_plane_cluster1_deployment_emailservice` doesn't have a matching start tag.

---
Report generated by [snippet-bot](https://github.com/apps/snippet-bot).
If you find problems with this result, please file an issue at:
https://github.com/googleapis/repo-automation-bots/issues.

**Comment by tmatsuo** [comment]
FYI @askmeegs

**Comment by bourgeoisor** [comment]
This repository is archived in favour of https://github.com/GoogleCloudPlatform/anthos-service-mesh-samples
